/* Autogenerated file. Do not edit manually. */

import { TableId } from "@latticexyz/utils";
import { defineComponent, Type as RecsType, World } from "@latticexyz/recs";

export function defineContractComponents(world: World) {
  return {
    BattleMap: (() => {
      const tableId = new TableId("", "BattleMap");
      return defineComponent(
        world,
        {
          gamecreatedby: RecsType.String,
          gamestart: RecsType.Boolean,
          width: RecsType.Number,
          height: RecsType.Number,
          gamepaused: RecsType.Boolean,
          gameend: RecsType.Boolean,
          winner: RecsType.String,
        },
        {
          metadata: {
            contractId: tableId.toHexString(),
            tableId: tableId.toString(),
          },
        }
      );
    })(),
    MapMembers: (() => {
      const tableId = new TableId("", "MapMembers");
      return defineComponent(
        world,
        {
          members: RecsType.StringArray,
        },
        {
          metadata: {
            contractId: tableId.toHexString(),
            tableId: tableId.toString(),
          },
        }
      );
    })(),
    BmItem: (() => {
      const tableId = new TableId("", "BmItem");
      return defineComponent(
        world,
        {
          itemtype: RecsType.Number,
          buff: RecsType.Number,
          mapId: RecsType.String,
        },
        {
          metadata: {
            contractId: tableId.toHexString(),
            tableId: tableId.toString(),
          },
        }
      );
    })(),
    BmPlayer: (() => {
      const tableId = new TableId("", "BmPlayer");
      return defineComponent(
        world,
        {
          mapId: RecsType.String,
          player: RecsType.String,
          ft: RecsType.Number,
          stake: RecsType.Number,
          dead: RecsType.Boolean,
        },
        {
          metadata: {
            contractId: tableId.toHexString(),
            tableId: tableId.toString(),
          },
        }
      );
    })(),
    BmPosition: (() => {
      const tableId = new TableId("", "BmPosition");
      return defineComponent(
        world,
        {
          x: RecsType.Number,
          y: RecsType.Number,
        },
        {
          metadata: {
            contractId: tableId.toHexString(),
            tableId: tableId.toString(),
          },
        }
      );
    })(),
    SpawnPos: (() => {
      const tableId = new TableId("", "SpawnPos");
      return defineComponent(
        world,
        {
          x: RecsType.NumberArray,
          y: RecsType.NumberArray,
        },
        {
          metadata: {
            contractId: tableId.toHexString(),
            tableId: tableId.toString(),
          },
        }
      );
    })(),
    ItemPos: (() => {
      const tableId = new TableId("", "ItemPos");
      return defineComponent(
        world,
        {
          x: RecsType.NumberArray,
          y: RecsType.NumberArray,
        },
        {
          metadata: {
            contractId: tableId.toHexString(),
            tableId: tableId.toString(),
          },
        }
      );
    })(),
    BmObstruction: (() => {
      const tableId = new TableId("", "BmObstruction");
      return defineComponent(
        world,
        {
          value: RecsType.Boolean,
        },
        {
          metadata: {
            contractId: tableId.toHexString(),
            tableId: tableId.toString(),
          },
        }
      );
    })(),
  };
}
