// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { Encounter, EncounterData, EncounterTableId } from "./tables/Encounter.sol";
import { EncounterTrigger, EncounterTriggerTableId } from "./tables/EncounterTrigger.sol";
import { Encounterable, EncounterableTableId } from "./tables/Encounterable.sol";
import { MapConfig, MapConfigTableId } from "./tables/MapConfig.sol";
import { MonsterCatchAttempt, MonsterCatchAttemptTableId } from "./tables/MonsterCatchAttempt.sol";
import { Monster, MonsterTableId } from "./tables/Monster.sol";
import { Movable, MovableTableId } from "./tables/Movable.sol";
import { Obstruction, ObstructionTableId } from "./tables/Obstruction.sol";
import { OwnedBy, OwnedByTableId } from "./tables/OwnedBy.sol";
import { Player, PlayerTableId } from "./tables/Player.sol";
import { Position, PositionTableId } from "./tables/Position.sol";
import { BattleMap, BattleMapTableId } from "./tables/BattleMap.sol";
import { MapMembers, MapMembersTableId } from "./tables/MapMembers.sol";
import { BmItem, BmItemTableId } from "./tables/BmItem.sol";
import { BmPlayer, BmPlayerTableId } from "./tables/BmPlayer.sol";
import { BmPosition, BmPositionTableId } from "./tables/BmPosition.sol";
import { SpawnPos, SpawnPosTableId } from "./tables/SpawnPos.sol";
import { ItemPos, ItemPosTableId } from "./tables/ItemPos.sol";
import { BmObstruction, BmObstructionTableId } from "./tables/BmObstruction.sol";
