// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { BattleMap, BattleMapTableId } from "./tables/BattleMap.sol";
import { MapMembers, MapMembersTableId } from "./tables/MapMembers.sol";
import { BmItem, BmItemTableId } from "./tables/BmItem.sol";
import { BmPlayer, BmPlayerData, BmPlayerTableId } from "./tables/BmPlayer.sol";
import { BmPosition, BmPositionTableId } from "./tables/BmPosition.sol";
import { SpawnPos, SpawnPosTableId } from "./tables/SpawnPos.sol";
import { BmPlayerCount, BmPlayerCountTableId } from "./tables/BmPlayerCount.sol";
import { BmItemCount, BmItemCountTableId } from "./tables/BmItemCount.sol";
import { BmObstruction, BmObstructionTableId } from "./tables/BmObstruction.sol";
