// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IBattleInitSystem {
  function createGame(
    uint32 width,
    uint32 height,
    address playerAddress,
    uint256 stake,
    uint32 playerlimit,
    string memory roomname
  ) external;

  function registerPlayer(bytes32 mapId, uint256 stake, address playerAddress) external;

  function setStake(bytes32 mapId, uint256 stake, address playerAddress) external;

  function spawnPlayers(bytes32 mapId) external;

  function spawnItems(bytes32 mapId) external;

  function startGame(bytes32 mapId, address playerAddress) external;
}
