// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IBattleMapSystem {
  function createGame(uint32 width, uint32 height) external;

  function move(bytes32 mapId, uint32 x, uint32 y) external;
}
