// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IBattleMapSystem {
  function pauseGame(bytes32 mapId, address playerAddress) external;

  function endGame(bytes32 mapId, address playerAddress) external;

  function move(bytes32 mapId, uint32 x, uint32 y, address playerAddress) external returns (bool);

  function sMove(bytes32 mapId, uint32 x, uint32 y, address playerAddress) external;

  function checkBattleResults(bytes32 mapId, bytes32 player1, bytes32 player2) external view returns (bytes32);

  function checkItemExists(bytes32 mapId, uint32 x, uint32 y) external view returns (bool, int32);

  function deleteGame(bytes32 mapId, address playerAddress) external;
}
